spring.application.name=catalog-service
management.server.port=8081
server.shutdown=graceful
management.endpoints.web.exposure.include=health,info,openapi,swagger-ui
management.info.git.mode=full
springdoc.use-management-port=true
