org.eclipse.jdt.core.compiler.compliance=21
org.eclipse.jdt.core.compiler.source=21
org.eclipse.jdt.core.compiler.codegen.targetPlatform=21
org.eclipse.jdt.core.formatter.lineSplit=80
org.eclipse.jdt.core.formatter.comment.line_length=80
org.eclipse.jdt.core.formatter.tabulation.char=space
org.eclipse.jdt.core.formatter.tabulation.size=4
org.eclipse.jdt.core.formatter.indentation.size=4
org.eclipse.jdt.core.formatter.join_wrapped_lines=false
org.eclipse.jdt.core.formatter.alignment_for_annotations_on_field=49
org.eclipse.jdt.core.formatter.alignment_for_annotations_on_parameter=49
org.eclipse.jdt.core.formatter.alignment_for_record_components=49
org.eclipse.jdt.core.formatter.parentheses_positions_in_record_declaration=common_lines
org.eclipse.jdt.core.formatter.brace_position_for_record_declaration=end_of_line
